service: aws-nodejs-typescript-express

package:
  patterns:
    - '!./**'
    - 'dist/**'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: eu-central-1

  httpApi:
    payload: '2.0'
    cors: true

functions:
  appPreflight: # allow unauthorized OPTIONS (preflight) requests
    handler: dist/index.handler # after 'npm run package' index.ts is transpiled to dist/index.js
    events:
      - httpApi: OPTIONS /{proxy+}
  app: # the default 'catch all' route only
    handler: dist/index.handler # after 'npm run package' index.ts is transpiled to dist/index.js
    events:
      - httpApi:
          method: '*'
          path: '*'
